---
:url: http://catalogue-scd.univ-paris-diderot.fr/cgi-bin/gw_48_1_14_1/chameleon?
:headers:
  Host: catalogue-scd.univ-paris-diderot.fr
  Referer: http://catalogue-scd.univ-paris-diderot.fr/cgi-bin/gw_48_1_14_1/chameleon?sessionid=42&skin=paris7&lng=fr&inst=consortium&timedout=1
  User-Agent: 'BUP7 Ruby API v0.1 +github.com/bfontaine/BUP7_API'
:limits:
  :keywords: 3
:values:
  :keywords:
    :title: 4
    :author: 1003
    :subject: 21
    :ISBN: 7
    :ISSN: 8
    :editor: 1018
    :collection: 1020
    :all_words: 1035

  :libraries:
    :all: 0
    :lsh: 1
    :sciences: 1
    :health: 2
    :central: 3
    :bichat: 4
    :english_studies: 5
    :robert_debre: 6
    :GHSS: 7
    :odontology: 8
    :physics: 9
    :hematology: 10
    :villemin: 11

  :documents:
    :all: norestriction
    :books: 0
    :CDroms: 1
    :DVDroms: 1
    :maps: 2
    :periodicals: 3
    :VHS: 4
    :DVD: 4
    :handouts: 5
    :annals: 5
    :thesis: 6

  :langs:
    :fr: fre
    :en: eng

:labels:
  :keywords_types:
    - [u1, vu1]
    - [u2, vu2]
    - [u3, vu3]
    - [u4, vu4]
    - [u5, vu5]

  :keywords:
    - [t1, vt1]
    - [t2, vt2]
    - [t3, vt3]
    - [t4, vt4]
    - [t5, vt5]

  :operations:
    - [op1, vop1]
    - [op2, vop2]
    - [op3]

  :libraries: choixbib

  :floc: floc

  :document_types: choixType

  :langs: flang
  :langs_inc: flangb

  :after: fpds
  :before: fpde

:consts:
  beginsrch: 1
  elementcount: 5
  flocb: 1
  fltset: submsn
  function: INITREQ
  inst: consortium
  lng: fr
  pos: 1
  rootsearch: KEYWORD
  search: KEYWORD
  sessionid: 42
  skin: paris7
  submittheform:
  usersrch: 1

:parsing:
  :attrs:
    :title: 'Titre :'
    :author: 'Auteur :'
    :editor: 'Editeur :'
    :ISBN: 'ISBN :'
    :notes: 'Notes :'
    :subjects: 'Sujets :'
    :cote: 'Cote :'

